
spring:
  profiles: 
    active: prod
  application:
    name: REACTIVE-SPRING-BOOT-APP  
# ==============================================================
# = Datasource/JPA config   
# ==============================================================              
  datasource:
    url: jdbc:mysql://mysql:3306/testdb?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
# By default Spring uses jpa.SpringNamingStrategy to generate the table names.
# The ImprovedNamingStrategy will convert CamelCase to SNAKE_CASE
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    

#Inseriamo il numero della porta
server:
  port: 8080
 
management:
  endpoints:
    web:
      exposure:
        include: health,info,httptrace,metrics,refresh,bus-refresh,hystrix.stream
